version: '2'
services:
  nifi:
    build: .
    container_name: nifi
    restart: always
    ports:
      - 2181
      - 2888
      - 3888
      - 9001
      - "8080:8080"
    volumes:
      - ./conf:/opt/nifi-conf
