- hosts: localhost
  connection: local

  roles:
    - nifi_secure

  vars_prompt:

    - name: "HOSTNAME"
      prompt: "Hostname of the NiFi instance."
      default: "localhost"
      private: no

    - name: "NIFI_VERSION"
      prompt: "Version of NiFi you wish to build"
      default: "1.1.1"
      private: no

  vars:
    HOSTNAME: localhost
    NIFI_VERSION: 1.1.1
    NIFI_CLIENT_NAME: "nifi-user"
