- hosts: localhost
  connection: local

  tasks:

    - name: Download Binaries
      command: "wget https://archive.apache.org/dist/nifi/{{NIFI_VERSION}}/nifi-{{NIFI_VERSION}}-bin.tar.gz -o {{PWD}}/nifi-archive.zip"
      args:
        creates: "{{PWD}}/nifi-archive.zip"

    - name: make unzip destination
      file:
        path: nifi-archive
        state: directory

    - name: unzip archive
      unarchive:
        src: nifi-archive.zip
        dest: nifi-archive

    - name: interpolate nifi.properties
      template:
        src: "conf/nifi.properties"
        dest: "{{HOSTNAME}}/nifi.properties"

    - name: interpolate template
      template:
        src: templates/Dockerfile
        dest: ./Dockerfile

    - name: build image
      command: "docker build -t nifi ."


  vars:
    PWD: "{{ lookup('env','PWD') }}"
    HOSTNAME: localhost
    NIFI_VERSION: 1.1.1
    PORTS:
      - 2181
      - 2888
      - 3888
      - 9001
      - 8080
